"""empty message

Revision ID: 05fb290542ee
Revises: f98bbe765d59
Create Date: 2020-07-18 09:07:29.903017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05fb290542ee'
down_revision = 'f98bbe765d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brand', 'enterprise_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('brand_ibfk_1', 'brand', type_='foreignkey')
    op.create_foreign_key(None, 'brand', 'enterprise', ['enterprise_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brand', type_='foreignkey')
    op.create_foreign_key('brand_ibfk_1', 'brand', 'enterprise', ['enterprise_id'], ['id'])
    op.alter_column('brand', 'enterprise_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
