"""empty message

Revision ID: 2814ccfc0c31
Revises: 05fb290542ee
Create Date: 2020-07-27 13:18:56.199041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2814ccfc0c31'
down_revision = '05fb290542ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('orders_count', sa.Integer(), nullable=True))
    op.drop_constraint('integration_ibfk_3', 'integration', type_='foreignkey')
    op.create_foreign_key(None, 'integration', 'brand', ['brand_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('line_item', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('line_item_ibfk_1', 'line_item', type_='foreignkey')
    op.create_foreign_key(None, 'line_item', 'order', ['order_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('order', sa.Column('integration_id', sa.Integer(), nullable=False))
    op.drop_constraint('order_ibfk_1', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'integration', ['integration_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'order', 'brand', ['brand_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index('code', table_name='platform')
    op.drop_column('platform', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform', sa.Column('code', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('code', 'platform', ['code'], unique=True)
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_ibfk_1', 'order', 'brand', ['brand_id'], ['id'])
    op.drop_column('order', 'integration_id')
    op.drop_constraint(None, 'line_item', type_='foreignkey')
    op.create_foreign_key('line_item_ibfk_1', 'line_item', 'order', ['order_id'], ['id'])
    op.alter_column('line_item', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'integration', type_='foreignkey')
    op.create_foreign_key('integration_ibfk_3', 'integration', 'brand', ['brand_id'], ['id'])
    op.drop_column('clients', 'orders_count')
    # ### end Alembic commands ###
