"""empty message

Revision ID: 31ae80ad5a29
Revises: c4fef56badd9
Create Date: 2020-08-03 17:35:09.883052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31ae80ad5a29'
down_revision = 'c4fef56badd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('code', table_name='platform')
    op.drop_column('platform', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform', sa.Column('code', mysql.VARCHAR(length=120), nullable=True))
    op.create_index('code', 'platform', ['code'], unique=True)
    # ### end Alembic commands ###
