"""empty message

Revision ID: 5096192f55f8
Revises: bf19ad911d53
Create Date: 2020-07-27 10:24:57.334319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5096192f55f8'
down_revision = 'bf19ad911d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('code', table_name='platform')
    op.drop_column('platform', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform', sa.Column('code', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('code', 'platform', ['code'], unique=True)
    # ### end Alembic commands ###
