"""empty message

Revision ID: 59027318ae7c
Revises: bc157bff7657
Create Date: 2020-08-04 15:55:36.359456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59027318ae7c'
down_revision = 'bc157bff7657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('customer_id_platform', sa.String(length=12), nullable=True))
    op.drop_index('customer_id_justeat', table_name='clients')
    op.create_unique_constraint(None, 'clients', ['customer_id_platform'])
    op.drop_column('clients', 'customer_id_justeat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('customer_id_justeat', mysql.VARCHAR(length=12), nullable=True))
    op.drop_constraint(None, 'clients', type_='unique')
    op.create_index('customer_id_justeat', 'clients', ['customer_id_justeat'], unique=True)
    op.drop_column('clients', 'customer_id_platform')
    # ### end Alembic commands ###
