"""empty message

Revision ID: 7c847965d729
Revises: 36e542a26602
Create Date: 2020-07-17 17:54:32.220421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c847965d729'
down_revision = '36e542a26602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client__platform')
    op.add_column('brand', sa.Column('enterprise_id', sa.Integer(), nullable=False))
    op.drop_constraint('brand_ibfk_1', 'brand', type_='foreignkey')
    op.create_foreign_key(None, 'brand', 'enterprise', ['enterprise_id'], ['id'])
    op.drop_column('brand', 'enterprise_to_id')
    op.add_column('integration', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.drop_constraint('integration_ibfk_1', 'integration', type_='foreignkey')
    op.create_foreign_key(None, 'integration', 'brand', ['brand_id'], ['id'])
    op.drop_column('integration', 'brand_to_id')
    op.add_column('order', sa.Column('platform_id', sa.Integer(), nullable=False))
    op.add_column('order', sa.Column('review', sa.Float(), nullable=True))
    op.drop_constraint('order_ibfk_3', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'platform', ['platform_id'], ['id'])
    op.drop_column('order', 'integration_id')
    op.add_column('platform', sa.Column('code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform', 'code')
    op.add_column('order', sa.Column('integration_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_ibfk_3', 'order', 'integration', ['integration_id'], ['id'])
    op.drop_column('order', 'review')
    op.drop_column('order', 'platform_id')
    op.add_column('integration', sa.Column('brand_to_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'integration', type_='foreignkey')
    op.create_foreign_key('integration_ibfk_1', 'integration', 'brand', ['brand_to_id'], ['id'])
    op.drop_column('integration', 'brand_id')
    op.add_column('brand', sa.Column('enterprise_to_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'brand', type_='foreignkey')
    op.create_foreign_key('brand_ibfk_1', 'brand', 'enterprise', ['enterprise_to_id'], ['id'])
    op.drop_column('brand', 'enterprise_id')
    op.create_table('client__platform',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('review', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='client__platform_ibfk_1'),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name='client__platform_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
