"""empty message

Revision ID: b4e9af97a42b
Revises: c854d1b2c3cd
Create Date: 2020-07-11 09:25:05.272726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4e9af97a42b'
down_revision = 'c854d1b2c3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brand', 'enterprise_to_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('integration', 'brand_to_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('integration', 'platform_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('midata', 'brand_to_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('midata', 'integration_to_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('midata', 'integration_to_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('midata', 'brand_to_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('integration', 'platform_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('integration', 'brand_to_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('brand', 'enterprise_to_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
