"""empty message

Revision ID: bd07ad2f60ad
Revises: 7c847965d729
Create Date: 2020-07-17 18:37:43.020224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd07ad2f60ad'
down_revision = '7c847965d729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'platform', ['code'])
    op.create_unique_constraint(None, 'platform', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'platform', type_='unique')
    op.drop_constraint(None, 'platform', type_='unique')
    # ### end Alembic commands ###
