"""empty message

Revision ID: bf19ad911d53
Revises: a19ac42db796
Create Date: 2020-07-21 16:29:28.621798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf19ad911d53'
down_revision = 'a19ac42db796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('orders_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'orders_count')
    # ### end Alembic commands ###
