"""empty message

Revision ID: c4fef56badd9
Revises: cbd9da86c8c5
Create Date: 2020-08-03 17:30:54.142252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4fef56badd9'
down_revision = 'cbd9da86c8c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('customer_id_justeat', sa.String(length=12), nullable=True))
    op.drop_index('email', table_name='clients')
    op.create_unique_constraint(None, 'clients', ['customer_id_justeat'])
    op.drop_column('clients', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('email', mysql.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'clients', type_='unique')
    op.create_index('email', 'clients', ['email'], unique=True)
    op.drop_column('clients', 'customer_id_justeat')
    # ### end Alembic commands ###
