"""empty message

Revision ID: df7d1a59e357
Revises: 36ad6d5ca710
Create Date: 2020-07-13 18:00:41.311149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7d1a59e357'
down_revision = '36ad6d5ca710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('relation_integration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['relation_integration'], ['integration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform')
    # ### end Alembic commands ###
