"""empty message

Revision ID: e02e13503dba
Revises: b4e9af97a42b
Create Date: 2020-07-11 09:49:21.962225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e02e13503dba'
down_revision = 'b4e9af97a42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('midata')
    op.drop_table('integration')
    op.drop_table('platform')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('integration',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('API_key', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('platform_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand_to_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`deleted` in (0,1))', name='integration_chk_1'),
    sa.ForeignKeyConstraint(['brand_to_id'], ['brand.id'], name='integration_ibfk_1'),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name='integration_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('midata',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('detail', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('brand_to_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('integration_to_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['brand_to_id'], ['brand.id'], name='midata_ibfk_1'),
    sa.ForeignKeyConstraint(['integration_to_id'], ['integration.id'], name='midata_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
