"""empty message

Revision ID: f98bbe765d59
Revises: bd07ad2f60ad
Create Date: 2020-07-18 09:00:07.226035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f98bbe765d59'
down_revision = 'bd07ad2f60ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brand', 'enterprise_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brand', 'enterprise_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
